package com.beyond.event.driven.model.entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Table: amq_inbox_handled, RabbitMQ 已处理的消息
 *
 * @author MyBatisGenerator
 */
@Entity
@Table(name = "inbox_handled")
public class InboxHandled implements Serializable {
    /**
     * Field: id, ID，Hex(MD5(QueueName+MessageID))+Hex(DataLength) [PK]
     */
    @Id
    private String id;

    /**
     * Field: message_id, 消息 ID [FK|amq_inbox_message.message_id]
     */
    private String messageId;

    /**
     * Field: created_at, 记录创建时间
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table amq_inbox_handled
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * Getter of field: id, ID，Hex(MD5(QueueName+MessageID))+Hex(DataLength) [PK]
     */
    public String getId() {
        return id;
    }

    /**
     * Setter of field: id, ID，Hex(MD5(QueueName+MessageID))+Hex(DataLength) [PK]
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * Getter of field: message_id, 消息 ID [FK|amq_inbox_message.message_id]
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Setter of field: message_id, 消息 ID [FK|amq_inbox_message.message_id]
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId == null ? null : messageId.trim();
    }

    /**
     * Getter of field: created_at, 记录创建时间
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * Setter of field: created_at, 记录创建时间
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amq_inbox_handled
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", messageId=").append(messageId);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}