package com.beyond.event.driven.model.entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Table: amq_outbox_message, RabbitMQ 发送消息记录
 *
 * @author MyBatisGenerator
 */
@Entity
@Table(name = "outbox_message")
public class OutboxMessage implements Serializable {
    /**
     * Field: id, ID [PK]
     */
    @Id
    private Long id;

    /**
     * Field: message_id, 消息 ID
     */
    private String messageId;

    /**
     * Field: is_binary, 是否二进制消息 [Bool|0:否, 1:是]
     */
    private Byte isBinary;

    /**
     * Field: exchange, RabbitMQ Exchange
     */
    private String exchange;

    /**
     * Field: routing_key, RabbitMQ RoutingKey
     */
    private String routingKey;

    /**
     * Field: content_type, 内容类型, MIME-Type
     */
    private String contentType;

    /**
     * Field: message_type, 消息类型
     */
    private String messageType;

    /**
     * Field: created_at, 记录创建时间
     */
    private Date createdAt;

    /**
     * Field: properties, 消息属性
     */
    private String properties;

    /**
     * Field: header, 消息头
     */
    private String header;

    /**
     * Field: body, 消息体
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table amq_outbox_message
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * Getter of field: id, ID [PK]
     */
    public Long getId() {
        return id;
    }

    /**
     * Setter of field: id, ID [PK]
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter of field: message_id, 消息 ID
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Setter of field: message_id, 消息 ID
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId == null ? null : messageId.trim();
    }

    /**
     * Getter of field: is_binary, 是否二进制消息 [Bool|0:否, 1:是]
     */
    public Byte getIsBinary() {
        return isBinary;
    }

    /**
     * Setter of field: is_binary, 是否二进制消息 [Bool|0:否, 1:是]
     */
    public void setIsBinary(Byte isBinary) {
        this.isBinary = isBinary;
    }

    /**
     * Getter of field: exchange, RabbitMQ Exchange
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * Setter of field: exchange, RabbitMQ Exchange
     */
    public void setExchange(String exchange) {
        this.exchange = exchange == null ? null : exchange.trim();
    }

    /**
     * Getter of field: routing_key, RabbitMQ RoutingKey
     */
    public String getRoutingKey() {
        return routingKey;
    }

    /**
     * Setter of field: routing_key, RabbitMQ RoutingKey
     */
    public void setRoutingKey(String routingKey) {
        this.routingKey = routingKey == null ? null : routingKey.trim();
    }

    /**
     * Getter of field: content_type, 内容类型, MIME-Type
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * Setter of field: content_type, 内容类型, MIME-Type
     */
    public void setContentType(String contentType) {
        this.contentType = contentType == null ? null : contentType.trim();
    }

    /**
     * Getter of field: message_type, 消息类型
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * Setter of field: message_type, 消息类型
     */
    public void setMessageType(String messageType) {
        this.messageType = messageType == null ? null : messageType.trim();
    }

    /**
     * Getter of field: created_at, 记录创建时间
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * Setter of field: created_at, 记录创建时间
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter of field: properties, 消息属性
     */
    public String getProperties() {
        return properties;
    }

    /**
     * Setter of field: properties, 消息属性
     */
    public void setProperties(String properties) {
        this.properties = properties == null ? null : properties.trim();
    }

    /**
     * Getter of field: header, 消息头
     */
    public String getHeader() {
        return header;
    }

    /**
     * Setter of field: header, 消息头
     */
    public void setHeader(String header) {
        this.header = header == null ? null : header.trim();
    }

    /**
     * Getter of field: body, 消息体
     */
    public String getBody() {
        return body;
    }

    /**
     * Setter of field: body, 消息体
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amq_outbox_message
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", messageId=").append(messageId);
        sb.append(", isBinary=").append(isBinary);
        sb.append(", exchange=").append(exchange);
        sb.append(", routingKey=").append(routingKey);
        sb.append(", contentType=").append(contentType);
        sb.append(", messageType=").append(messageType);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", properties=").append(properties);
        sb.append(", header=").append(header);
        sb.append(", body=").append(body);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}