spring:
  application:
    name: beyond-rabc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/beyond-rabc?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: beyond
  jpa:
    show-sql: true

application:
  token:
    env: dev
    issuer: ${spring.application.name}
    audience: ${spring.application.name}


